services:
    prod:
        container_name: erelya-bot-prod
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DATABASE_URL: ${DATABASE_URL}
        image: erelya:latest
        restart: always
        env_file: .env.prod
    preview:
        container_name: erelya-bot-preview
        build:
            context: .
            dockerfile: Dockerfile
        image: erelya:preview
        restart: always
        env_file: .env.prod